/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutComponent: typeof import('./src/components/AboutComponent.vue')['default']
    CursorComponent: typeof import('./src/components/CursorComponent.vue')['default']
    ExerienceComponent: typeof import('./src/components/ExerienceComponent.vue')['default']
    FooterComponent: typeof import('./src/components/FooterComponent.vue')['default']
    GlobalHeader: typeof import('./src/components/GlobalHeader.vue')['default']
    HeroComponent: typeof import('./src/components/HeroComponent.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestimonialsComponent: typeof import('./src/components/TestimonialsComponent.vue')['default']
    WorkComponent: typeof import('./src/components/WorkComponent.vue')['default']
  }
}
